/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onsite_chic_StdIOCapturer */

#ifndef _Included_com_onsite_chic_StdIOCapturer
#define _Included_com_onsite_chic_StdIOCapturer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onsite_chic_StdIOCapturer
 * Method:    initNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_onsite_chic_StdIOCapturer_initNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_onsite_chic_StdIOCapturer
 * Method:    destroyNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onsite_chic_StdIOCapturer_destroyNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onsite_chic_StdIOCapturer
 * Method:    read
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onsite_chic_StdIOCapturer_read
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
